#
# version.cmake : version du projet
#

set (PYTHON_UTIL_MAJOR_VERSION "6")
set (PYTHON_UTIL_MINOR_VERSION "2")
set (PYTHON_UTIL_RELEASE_VERSION "1")
set (PYTHON_UTIL_VERSION ${PYTHON_UTIL_MAJOR_VERSION}.${PYTHON_UTIL_MINOR_VERSION}.${PYTHON_UTIL_RELEASE_VERSION})

