name: Spack/Ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    uses: LIHPC-Computational-Geometry/lihpccg-ci/spack-ubuntu.yml@main
    with:
      run-tests: false
      cmake-options: "-DUSE_PYTHON_3:BOOL=ON"
